on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/grawgo
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v8.3.2
      - run: uvx ruff format --check
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
